/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordcount;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WordCountTest {
    @Test
    void handleInput_OneWord_SaysNumberIsOne() {
        String input = "foo";
        String expectedOutput = "Number of words: 1";
        WordCount wordCount = new WordCount();

        String output = wordCount.handleInput(input);

        assertEquals(output, expectedOutput);
    }
}
